#!/usr/bin/env perl
#
# Copyright (C) 2009-2018 Foswiki Contributors
#
# For licensing info read LICENSE file in the Foswiki root.
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details, published at 
# http://www.gnu.org/copyleft/gpl.html

use strict;
use warnings;

use File::Spec();

# Set library paths in @INC, at compile time
BEGIN {
    my ( $volume, $currDir, $action ) = File::Spec->splitpath(__FILE__);
    $currDir .= '/' if $currDir;
    my $setlib = File::Spec->catpath( $volume, "$currDir../bin", 'setlib.cfg' );
    @INC = ( '.', grep { $_ ne '.' } @INC ) unless $currDir;
    require $setlib;
}

use Foswiki ();
use Foswiki::Contrib::Stringifier ();

my $fileName = $ARGV[0] ;
die "no filename" unless $fileName;

$fileName = Cwd::abs_path($fileName);
die "can't read $fileName" unless -r $fileName;

my $stringifier = new Foswiki::Contrib::Stringifier();
my $text = $stringifier->stringFor($fileName);
binmode(STDOUT, ":utf8");
print $text."\n" if $text;

1;
